name: Update Configs
permissions: write-all

on:
  push:
    branches:
      - main
  schedule:
    # Run every 9 minutes
    - cron: "*/9 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: cd Files && pip install -r requirements.txt

    - name: Run Python script and save output to file
      run: cd Files && python app.py
      
    - name: Run Splitter script and save output to file
      run: cd Files && python sort.py

    - name: Commit and push files
      uses: EndBug/add-and-commit@v7
      with:
        author_name: "Alexanderr"
        author_email: "isgenderowgundogdy8@github.com"
        message: "Tazejeee🔥❤️‍🔥🎆"
        add: "."
        push: "https://github.com/alexanderofficial09/testtt.git"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
